Added Bridge category
securing/SCSVS pull request #17
Opened 2022-03-11 15:50 UTC by damianrusinek

2022-06-14 10:01 UTC, whereispawel requested changes
Minor changes, almost ready to publish ;)

2022-06-14 10:01 UTC, wh01s7 commented on 2.0/0x200-Components/0x206-C6-Bridge.md
> +If a project contains an Bridge smart contract, it is necessary to follow the standard and create a secure contract based on it. Learn from past mistakes that have been identified and have solutions
Gramma
```suggestion
If a project contains a Bridge smart contract, it is necessary to follow the standard and create a secure contract based on it. Learn from past mistakes that have been identified and have solutions ready.
```

2022-06-14 10:01 UTC, wh01s7 commented on 2.0/0x200-Components/0x206-C6-Bridge.md
> +
Add references

```suggestion

## References

For more information, see also:

* [EEA Crosschain Security Guidelines Version 1.0](https://entethalliance.github.io/crosschain-interoperability/crosschainsecurityguidelines.html)
* [Open problems in cross-chain protocols](https://arxiv.org/pdf/2101.12412.pdf)
* [Cross Chain Awareness](https://docs.openzeppelin.com/contracts/4.x/api/crosschain)
* [The Dark Side of DeFi: Cross-Chain Bridge Hacks](https://quantstamp.com/blog/the-dark-side-of-defi-cross-chain-bridge-hacks/)
* [What Are Cross-Chain Smart Contracts?](https://blog.chain.link/cross-chain-smart-contracts/)
* [Aurora Inflation Spend Bugfix Review](https://medium.com/immunefi/aurora-infinite-spend-bugfix-review-6m-payout-e635d24273d)
* [WORMHOLE - REKT](https://rekt.news/wormhole-rekt/)
* [RONIN NETWORK - REKT](https://rekt.news/ronin-rekt/)
```

2022-06-14 10:01 UTC, wh01s7 commented on 2.0/0x200-Components/0x206-C6-Bridge.md
> +| **C6.6** | Verify that bridge uses a nonce parameter to allow the same operation (the same sender, receiver and amount) to be executed multiple times. |
(C6.7) I think about cases where seeing someone's transaction, it can be FR and use input data to call a function other than what the user wanted. Everything signed correctly, but misused. 

Of course, this is partially solved by C6.1, but maybe it's worth adding such a point anyway. What do you think?
```suggestion
| **C6.6** | Verify that bridge uses a nonce parameter to allow the same operation (the same sender, receiver and amount) to be executed multiple times. |
| **C6.7** | Verify signed message cannot be used in a context other than as assumed. |
```

2022-06-15 10:03 UTC, damianrusinek commented on 2.0/0x200-Components/0x206-C6-Bridge.md
> +| **C6.6** | Verify that bridge uses a nonce parameter to allow the same operation (the same sender, receiver and amount) to be executed multiple times. |
Yeah, that's good. I also added EIP-712 to references and link to it in this req.

2022-06-15 10:13 UTC, whereispawel approved these changes
Good to go

2022-06-15 10:13 UTC, merged